name: KGlam
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  timeago: ^3.6.1
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  flutter_local_notifications: ^19.5.0
  intl: ^0.18.1
  pinput: ^6.0.0
  curved_navigation_bar: ^1.0.6
  fluttertoast: ^9.0.0
  video_player: ^2.10.1
  provider: ^6.1.5+1
  image_picker: ^1.2.1
  modal_progress_hud_nsn: ^0.5.1
  shared_preferences: ^2.5.4
  http: ^1.6.0
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  app_settings: ^7.0.0
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/nativeSplash.png"
  remove_alpha: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/video/
